[versions]
# Fabric dependencies
# The latest versions are available at https://fabricmc.net/develop
minecraft = "1.19.1"
mappings = "1.19.1+build.1"
loader = "0.14.8"
fabric = "0.58.5+1.19.1"

# Fabric loom
loom = "0.12-SNAPSHOT"

# Mod dependencies
sodium = "mc1.19-0.4.2"
iris = "1.19.x-v1.2.6"
clothconfig = "7.0.73"
modmenu = "4.0.5"

# Other dependencies
joml = "1.10.4"
jccp = "1.4.14"
lombok = "1.18.24"

[libraries]
# Minecraft
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Fabric
fabric_mappings = { module = "net.fabricmc:yarn", version.ref = "mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

# Mod dependencies
mod_sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
mod_iris = { module = "maven.modrinth:iris", version.ref = "iris" }
mod_clothconfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothconfig" }
mod_modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Other dependencies
joml = { module = "org.joml:joml", version.ref = "joml" }
jccp = { module = "org.anarres:jcpp", version.ref = "jccp" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
licenser = { id = "org.cadixdev.licenser", version = "0.6.1" }